# -*- coding: utf-8 -*-
"""code1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13PAaBxfh0RP4SD-bgh8z6FYIR1M2AbH6
"""

# ================================
# IMPORT LIBRARIES
# ================================

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (
    train_test_split,
    KFold,
    cross_val_score
)

from sklearn.preprocessing import (
    StandardScaler,
    PolynomialFeatures
)

from sklearn.linear_model import LinearRegression

from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

from scipy import stats

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

# ================================
# LOAD DATA
# ================================

df = pd.read_excel("gym_members_exercise_tracking.xlsx")

print("\nDATA SHAPE")
print(df.shape)

print("\nFIRST 5 ROWS")
print(df.head())

# ================================
# BASIC INSPECTION
# ================================

print("\nINFO")
print(df.info())

print("\nMISSING VALUES")
print(df.isnull().sum())

print("\nDESCRIPTIVE STATISTICS")
print(df.describe())

# ================================
# PREPROCESSING
# ================================

if 'BMI' in df.columns:
    df.drop('BMI', axis=1, inplace=True)

df['Gender'] = (df['Gender'] == 'Male').astype(int)

df = pd.get_dummies(
    df,
    columns=['Workout_Type'],
    drop_first=True,
    dtype=int
)

print("\nDATA TYPES AFTER PREPROCESSING")
print(df.dtypes)

# ================================
# EDA
# ================================

plt.figure(figsize=(8,5))
plt.hist(df['Calories_Burned'], bins=30)
plt.title('Distribution of Calories Burned')
plt.xlabel('Calories Burned')
plt.ylabel('Frequency')
plt.show()

corr = df.corr(numeric_only=True)

plt.figure(figsize=(12,8))
sns.heatmap(
    corr,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)
plt.title('Correlation Heatmap')
plt.show()

print("\nCORRELATION WITH TARGET")
print(
    corr['Calories_Burned']
    .sort_values(ascending=False)
)

plt.figure(figsize=(7,5))
plt.scatter(
    df['Session_Duration (hours)'],
    df['Calories_Burned']
)
plt.xlabel('Session Duration')
plt.ylabel('Calories Burned')
plt.title('Session Duration vs Calories Burned')
plt.show()

# ================================
# DEFINE X AND y
# ================================

X = df.drop('Calories_Burned', axis=1)
y = df['Calories_Burned']

# ================================
# VIF ANALYSIS
# ================================

X_vif = sm.add_constant(X)

vif_df = pd.DataFrame()

vif_df["Variable"] = X_vif.columns

vif_df["VIF"] = [
    variance_inflation_factor(
        X_vif.values,
        i
    )
    for i in range(X_vif.shape[1])
]

print("\nVIF TABLE")
print(
    vif_df.sort_values(
        'VIF',
        ascending=False
    )
)

# ================================
# TRAIN TEST SPLIT
# ================================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

# ================================
# STANDARDIZATION
# ================================

scaler = StandardScaler()

X_train_sc = scaler.fit_transform(X_train)
X_test_sc = scaler.transform(X_test)

# ================================
# MULTIPLE LINEAR REGRESSION
# ================================

mlr = LinearRegression()

mlr.fit(
    X_train_sc,
    y_train
)

y_pred_mlr = mlr.predict(
    X_test_sc
)

# ================================
# MLR EVALUATION
# ================================

rmse_mlr = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_mlr
    )
)

mae_mlr = mean_absolute_error(
    y_test,
    y_pred_mlr
)

r2_mlr = r2_score(
    y_test,
    y_pred_mlr
)

n = len(y_test)
p = X_test.shape[1]

adj_r2_mlr = 1 - (
    (1-r2_mlr)*(n-1)
    /(n-p-1)
)

print("\nMLR RESULTS")
print("RMSE =", rmse_mlr)
print("MAE =", mae_mlr)
print("R2 =", r2_mlr)
print("Adjusted R2 =", adj_r2_mlr)

# ================================
# COEFFICIENT TABLE
# ================================

coef_df = pd.DataFrame({
    'Variable': X.columns,
    'Coefficient': mlr.coef_
})

coef_df = coef_df.sort_values(
    'Coefficient',
    key=abs,
    ascending=False
)

print("\nCOEFFICIENT TABLE")
print(coef_df)

# ================================
# RESIDUAL ANALYSIS
# ================================

residuals_mlr = y_test - y_pred_mlr

plt.figure(figsize=(7,5))
plt.scatter(
    y_pred_mlr,
    residuals_mlr
)

plt.axhline(
    y=0,
    color='red',
    linestyle='--'
)

plt.xlabel('Predicted')
plt.ylabel('Residuals')
plt.title('Residual Plot')
plt.show()

plt.figure(figsize=(7,5))
sns.histplot(
    residuals_mlr,
    kde=True
)
plt.title('Distribution of Residuals')
plt.show()

sm.qqplot(
    residuals_mlr,
    line='45'
)
plt.show()

w_stat, p_shapiro = stats.shapiro(
    residuals_mlr
)

print("\nSHAPIRO-WILK TEST")
print("W =", w_stat)
print("p-value =", p_shapiro)

# ================================
# DEGREE SELECTION
# ================================

kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

degree_results = []

for degree in [1,2,3]:

    poly = PolynomialFeatures(
        degree=degree,
        include_bias=False
    )

    X_poly = poly.fit_transform(
        X_train_sc
    )

    model = LinearRegression()

    cv_rmse = np.sqrt(
        -cross_val_score(
            model,
            X_poly,
            y_train,
            cv=kf,
            scoring='neg_mean_squared_error'
        )
    )

    degree_results.append([
        degree,
        cv_rmse.mean(),
        cv_rmse.std()
    ])

degree_df = pd.DataFrame(
    degree_results,
    columns=[
        'Degree',
        'Mean RMSE',
        'SD'
    ]
)

print("\nDEGREE SELECTION")
print(degree_df)

plt.figure(figsize=(6,4))
plt.plot(
    degree_df['Degree'],
    degree_df['Mean RMSE'],
    marker='o'
)
plt.xlabel('Degree')
plt.ylabel('Mean RMSE')
plt.title('Polynomial Degree Selection')
plt.show()

# ================================
# POLYNOMIAL REGRESSION
# ================================

poly = PolynomialFeatures(
    degree=2,
    include_bias=False
)

X_train_poly = poly.fit_transform(
    X_train_sc
)

X_test_poly = poly.transform(
    X_test_sc
)

pr = LinearRegression()

pr.fit(
    X_train_poly,
    y_train
)

y_pred_pr = pr.predict(
    X_test_poly
)

# ================================
# POLYNOMIAL EVALUATION
# ================================

rmse_pr = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred_pr
    )
)

mae_pr = mean_absolute_error(
    y_test,
    y_pred_pr
)

r2_pr = r2_score(
    y_test,
    y_pred_pr
)

p_poly = X_test_poly.shape[1]

adj_r2_pr = 1 - (
    (1-r2_pr)*(n-1)
    /(n-p_poly-1)
)

print("\nPOLYNOMIAL RESULTS")
print("RMSE =", rmse_pr)
print("MAE =", mae_pr)
print("R2 =", r2_pr)
print("Adjusted R2 =", adj_r2_pr)

# ================================
# ACTUAL VS PREDICTED
# ================================

plt.figure(figsize=(6,5))
plt.scatter(
    y_test,
    y_pred_mlr
)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("MLR: Actual vs Predicted")
plt.show()

plt.figure(figsize=(6,5))
plt.scatter(
    y_test,
    y_pred_pr
)

plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--'
)

plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.title("Polynomial Regression: Actual vs Predicted")
plt.show()

# ================================
# CROSS VALIDATION COMPARISON
# ================================

rmse_mlr_folds = np.sqrt(
    -cross_val_score(
        LinearRegression(),
        X_train_sc,
        y_train,
        cv=kf,
        scoring='neg_mean_squared_error'
    )
)

rmse_pr_folds = np.sqrt(
    -cross_val_score(
        LinearRegression(),
        X_train_poly,
        y_train,
        cv=kf,
        scoring='neg_mean_squared_error'
    )
)

cv_results = pd.DataFrame({
    'Fold': range(1,6),
    'MLR_RMSE': rmse_mlr_folds,
    'PR_RMSE': rmse_pr_folds
})

print("\nCROSS VALIDATION RESULTS")
print(cv_results)

# ================================
# NORMALITY OF PAIRED DIFFERENCES
# (assumption of the paired t-test)
# ================================

diff_folds = rmse_mlr_folds - rmse_pr_folds

w_diff, p_diff = stats.shapiro(
    diff_folds
)

print("\nNORMALITY OF PAIRED DIFFERENCES (SHAPIRO-WILK)")
print("Differences =", diff_folds)
print("W =", w_diff)
print("p-value =", p_diff)

sm.qqplot(
    diff_folds,
    line='s'
)
plt.title('Q-Q Plot of Paired Differences')
plt.show()

# Distribution-free check: Wilcoxon signed-rank test
w_wil, p_wil = stats.wilcoxon(
    rmse_mlr_folds,
    rmse_pr_folds
)

print("\nWILCOXON SIGNED-RANK TEST")
print("Statistic =", w_wil)
print("P Value =", p_wil)

# ================================
# PAIRED T TEST
# ================================

t_stat, p_value = stats.ttest_rel(
    rmse_mlr_folds,
    rmse_pr_folds
)

print("\nPAIRED T TEST")
print("T Statistic =", t_stat)
print("P Value =", p_value)

mean_diff = diff_folds.mean()
sd_diff = diff_folds.std(ddof=1)
k = len(diff_folds)
t_crit = stats.t.ppf(0.975, k - 1)

ci_low = mean_diff - t_crit * sd_diff / np.sqrt(k)
ci_high = mean_diff + t_crit * sd_diff / np.sqrt(k)

print("Mean Difference =", mean_diff)
print("SD of Differences =", sd_diff)
print("95% CI =", (ci_low, ci_high))
print("Effect Size d_z =", mean_diff / sd_diff)

# ================================
# FINAL COMPARISON
# ================================

comparison = pd.DataFrame({
    'Metric': [
        'RMSE',
        'MAE',
        'R2',
        'Adjusted R2'
    ],
    'MLR': [
        rmse_mlr,
        mae_mlr,
        r2_mlr,
        adj_r2_mlr
    ],
    'Polynomial': [
        rmse_pr,
        mae_pr,
        r2_pr,
        adj_r2_pr
    ]
})

print("\nFINAL MODEL COMPARISON")
print(comparison)